### ISSUE TITLE
Problem with specific CSL styles

### ISSUE THREAD

**Issue by cadr10** [andras-simonyi/citeproc-el#13]
Hello.
When I try to export to html using these two csl files:

https://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas

https://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas-ufrgs

The first one gives the error _wrong type argument: sequencep, splice_
The second one:  Wrong type argument: listp, "[NO BIBLIOGRAPHY LAYOUT IN CSL STYLE]"

They are specific to these styles, since when I used an Astronomy style https://www.zotero.org/styles/annual-review-of-astronomy-and-astrophysics it worked fine.

Org mode version 9.4 (9.4-27-g47bf60-elpaplus @ /home/cadr/.emacs.d/elpa/org-plus-contrib-20201026/)

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28

citeproc-org installed with use-package and updated

**Comment by andras-simonyi** [comment]
(I transferred the issue here, because  it turned out to be citeproc-el related.) I think I managed to track down the problem with the second style file and pushed a change which should solve it (https://github.com/andras-simonyi/citeproc-el/commit/ff1608e4f520429de5e54b663a38db422c3d845f). Could you check whether this commit fixes the bug on your system?

**Comment by cadr10** [comment]
Hi! Thanks for the quick reply!
Updated and I was able to export to html with the second style. 
After playing around, I exported successfully with the first style. I changed the citation and it worked.
Thank you for this package and for the less than 24 hours fix! Really appreciated :-)
