### ISSUE TITLE
bibtex's @inbook redered incorrectly

### ISSUE THREAD

**Issue by coloquio** [andras-simonyi/citeproc-el#145]
I'm using org-cite to create a bibliography in a pdf document, and I'm having problems with the rendering of bibtex's @inbook using csl

 pdfcreator={Emacs 28.2 (Org mode 9.5.5)}, 
#+bibliography: /path/to/org/dupTest.bib
#+cite_export: csl  /path/to/org/csl/apa.csl

Bibtex entry:
 
@inbook{Giddens1974,
	author = {Giddens, Anthony},
	booktitle = {Elites and Power in British society},
	chapter = {Elites in the British Class Structure},
	editor = {Stanworth, Philip and Giddens, Anthony},
	pages = {22--44},
	publisher = {London, New York: Cambridge University Press},
	timestamp = {2010.02.15},
	year = {1974}
}

Converted in the *.tex file to:  (\citeprocitem{4}{Giddens, 1974})

rendered in pdf as: 
Giddens, A. (1974). In P. Stanworth & A. Giddens (Eds.), Elites and power
in british society (pp. 22-44). London, New York: Cambridge University
Press.

which:
+ misses the chapter's author and the chapter title
+ misses word capitalization in the book title. 
+ places chapter's page numbers wrongly after the book title (they should appear immediately before "in P: Stanworth... ")

AFAIK csl does not have the bibtex's type @inbook, which should be converted to the equivalent "chapter". Is citeproc working this way?  Am I making a wrong turn at some point? 

Sincerely,

**Comment by andras-simonyi** [comment]
Hello, unfortunately ˙inBook˙ type items are a little complicated, because on the BibTeX-side citeproc-el's main target is biblatex and `inBook` is one of the few entry types where biblatex is not fully BibTeX compatible. The simple fix is to use `title` instead of `chapter` (this is how biblatex expects the information). As for capitalization, this depends on the used CSL style,  the APA style you selected seems to  use lower case titles. (Note that you can still keep `British` in its capitalized form using the usual BibTeX "protecting braces", e.g., `{B}ritish}`).

**Comment by coloquio** [comment]
Thanks.
