### ISSUE TITLE
Feature Request: Allow locale-getter to default to a custom-set variable.

### ISSUE THREAD

**Issue by swflint** [andras-simonyi/citeproc-el#152]
In my packages [`org-cite-sidecar` and `ebib-sidecar`](https://git.sr.ht/~swflint/emacs-universal-sidecar) I create locale getters, and it would be helpful to instruct users to set a citeproc-variable instead of one per package.

**Comment by andras-simonyi** [comment]
I've looked into the package and it seems very interesting -- I'm happy that you are making use of citeproc-el in it. As for adding a defcustom, citeproc-el doesn't have customizable variables by design, because it is intended to be a low-level library which is not user-facing at all. If you want to delegate setting the CSL locales (and styles) directory to another package I recommend using the variables `org-cite-csl-locales-dir` and `org-cite-csl-styles-dir` in `oc-csl.el`, which is part of Org and, therefore, Emacs. Relying on Org in this respect could have the added benefit that it already provides a locale-getter creating function, and Org actually contains the default en_US CSL locale (and the Chicago author-date CSL style).

**Comment by swflint** [comment]
Thanks!  I'll take a look to see if I can use that.
