### ISSUE TITLE
parenthetical citations appear as footnotes

### ISSUE THREAD

**Issue by AlecVercruysse** [andras-simonyi/citeproc-el#158]
Hi, thank you very much for this package! Using the standard `ieee.csl` available [online](https://github.com/citation-style-language/styles/blob/master/ieee.csl), with the following MWE:
```
This is a test of adding a citation [cite:@guptaMicrowavesMetals2008]. 

The bibliography:
#+PRINT_BIBLIOGRAPHY:
```
Version 0.9.4 produces the following output upon HTML export:
![image](https://github.com/andras-simonyi/citeproc-el/assets/12777730/264c2f20-cfea-45fe-bc48-8fb199c26913)

Commit e3911d8 changed the behavior:
![image](https://github.com/andras-simonyi/citeproc-el/assets/12777730/c7cc0cc2-3a78-407f-b956-d5fc6c12a255)

Which feels unintended. [modern-language-association.csl](https://github.com/citation-style-language/styles/blob/master/modern-language-association.csl) similarly produces:
![image](https://github.com/andras-simonyi/citeproc-el/assets/12777730/b4adc502-7da0-4f52-a342-4b9a5c4771be)

I'm hoping to revert to the behavior where footnotes are not inserted. Thank you for the help!

**Comment by AlecVercruysse** [comment]
It turns out my org was outdated--I was on `e9c288dfa` (Emacs 29.1). Pulling the latest version fixed it. Thanks for the help and apologies for the erroneous report!

**Comment by kofm** [comment]
Sorry @andras-simonyi  for bumping this but I have the same exact issue. My Org mode version is 9.6.9. Citeproc is at the last commit. The problem is that no matter what csl style I use I always get in-text references as footnotes. Citation style within the footnote and bibliography changes according to the CSL used. Am I missing something? 

I simply put this in my org file:
`#+cite_export: csl chicago-author-date.csl`

and then in the text cite like this: `[cite:@IPCC2019Guidelines]`

Maybe it is not a bug but I couldn't find anything useful in the org manual.

**Comment by kofm** [comment]
Updating to 9.6.24 solves the problem. I wasn't able to solve the problem with the code in `main` since it completely broke org and particularly org-export. Sorry again for bothering you all
