### ISSUE TITLE
Add a "full-author-list" parameter

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/citeproc-el#16]
Related to #15, and from list discussion, this would allow support for the `org-cite` "full" variants.

It's probably lower priority than #15, but would be good to have?

**Comment by denismaier** [comment]
Problem with this: how does citeproc no how to render the full author list? Just ignore et-al-min?

**Comment by bdarcus** [comment]
> Problem with this: how does citeproc no how to render the full author list? Just ignore et-al-min?

Yes, I think so.

**Comment by bdarcus** [comment]
So actually, other parameter name could be something like "ignore-ibid"?

**Comment by andras-simonyi** [comment]
> So actually, other parameter name could be something like "ignore-ibid"?
> 
> Or maybe that just confuses things in some cases.

do you mean ignore-et-al? I mean, are we talking about printing out the full name list for all name variables irrespective of the set et-al  options?

**Comment by bdarcus** [comment]
> we talking about printing out the full name list for all name variables irrespective of the set et-al options?

AFAIK, yes. I'll edit the comment to clarify.

The use case is most common, I think, in "text" styles, where you don't want author shortening to happen; like:

> According to Doe, Smith and Jones (2018) ...

**Comment by denismaier** [comment]
> The use case is most common, I think, in "text" styles, where you don't want author shortening to happen; like:
> 
> > According to Doe, Smith and Jones (2018)

But isn't that what cite/text should be for?

**Comment by bdarcus** [comment]
No; this is for when the default would be:

> Doe at al (2018).

**Comment by denismaier** [comment]
> No; this is for when the default would be:
> 
> > Doe at al (2018).
> 
> It's a sub-style variant of cite/text (or cite/author).

Not sure.
CSL 1.1 will introduce a new dedicated element `cs:intext` or so that should cover exactly these kind of cases where the author part of the citation is different when it occurs in text vs in parentheses, e.g. APA:
(Doe & Smith, 2019)
vs.
Doe and Smith (2019) argue.

With this it should also be possible to have
(Doe et al, 2018)
vs
According to Doe, Smith, and Jones (2018).

In the absence of such a solution a "full-author-list" style/substyle makes sense, but I'd consider this a rather hackish solution to accomodate use cases that should be covered on a style level.

**Comment by bdarcus** [comment]
That's true, and it complicates this a bit.

Let me think a bit; I'll edit this if and when I have something helpful to say :-)

**Comment by andras-simonyi** [comment]
Closing as the merge of  #29  implemented the `ignore-et-al` switch for citations which is equivalent to `full-author-list`.
