### ISSUE TITLE
Add ODT export format

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/citeproc-el#23]
To accommodate people who need to target MS Word, etc, with real footnotes, etc.

**Comment by denismaier** [comment]
Shouldn't that be done on the org-side?

**Comment by bdarcus** [comment]
Yes, also, but ODT isn't a supported format here, according to the docs.

**Comment by denismaier** [comment]
I still don't get it. Wouldn't it make more sense to go through a common intermediary? E.g. org-syntax? So that citeproc-el doesn't have to do the formatting for all output formats.

**Comment by denismaier** [comment]
Maybe I'm to much influenced by pandoc here, but I would expect citeproc-el to work with all supported output formats out-of-the-box without further configuration.

**Comment by bdarcus** [comment]
IDK why the current design, but that's not how this library works. See:

https://github.com/andras-simonyi/citeproc-el/blob/master/citeproc-formatters.el

**Comment by andras-simonyi** [comment]
> I still don't get it. Wouldn't it make more sense to go through a common intermediary? E.g. org-syntax? So that citeproc-el doesn't have to do the formatting for all output formats.

The main reason for the existence of multiple `citeproc-el` formatting backends is that  Org markup  is not expressive enough to represent some of the formatting described by CSL styles, e.g., there is no Org representation of small caps or hanging indent. Because of these limitations, citeproc-el is designed to be able to provide richer export for important formats that can actually describe (some of) these formatting instructions like HTML and LaTeX, everything else can indeed use the Org `citeproc-el` backend as an intermediary.

For exporting Org documents with a particular backend using `citeproc-el` this means that the exporter has to use the dedicated `citeproc-el` backend for the format in question if it's available, and use the Org `citeproc-el` backend as a fallback. This ensures that citations and bibliographies can be exported in  any  format for which there is an Org exporter, and the exported documents will contain richer formatting than what would be possible with plain Org if there is a compatible dedicated `citeproc-el` backend.
