### ISSUE TITLE
When using the "new" org-mode citation system, citations in exponents are nor correctly exported.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [andras-simonyi/citeproc-el#32]
Almost all is the title : in styles prescribing citation calls by numbers in exponents, these citation calls are incorrectly rendered : 
- in ODT, they are rendered by a caret followed by the number wrapped in brackets : `^{xx}` ;
- the same rendering appears in LaTeX, giving a switch to math mode starting with the first citation. 

See the example (.org, .tex, .pdf and .odt)

A quick fix would be to wrap such citations in text math delimiters (`\(...\)` or dollars).

Issue #23 may be related...

[TstOrgCsl.zip](https://github.com/andras-simonyi/citeproc-el/files/6912541/TstOrgCsl.zip)

**Comment by andras-simonyi** [comment]
Thanks for reporting this! Hopefully the LaTeX problem has been at least partly fixed by commit d9b12a9  (switched to using `\textsuperscript` and `\textsubscript` for vertical align). The ODT problem seems to be a bit more difficult, because -- in absence of a dedicated citeproc-el formatter (which is planned BTW) -- the export uses the Org format as an intermediary and there seems to be a problem with exporting Org superscripts to ODT when the superscripted text follows one or more spaces. This leads to an important general problem with superscripted numeric citation styles like Nature: ideally, I think, this type of citations should immediately follow the word/punctuation preceding them, in contrast to other styles, e.g. author-date. Similarly to punctuation handling this is out of scope for `citeproc-el` and should be handled by the calling application, e.g. Org -- perhaps it would be worth raising this problem on the Org mailing list. (One difficulty is to determine whether a style is actually superscripted, this functionality actually could be provided by `citeproc-el` relatively easily.)

**Comment by andras-simonyi** [comment]
This is fixed by merging #45, so I'm closing the issue.

**Comment by andras-simonyi** [comment]
This is fixed by merging #45, so I'm closing the issue.
