### ISSUE TITLE
Fix "{{Literal}}" authors

### ISSUE THREAD

**Issue by salutis** [andras-simonyi/citeproc-el#72]
`author` BibTeX field `{{Indiana University}}` should render as "Indiana University" and not "I. University".

Tested with Pandoc and CSL: https://github.com/citation-style-language/styles/blob/master/apa.csl

**Comment by Quintus** [comment]
I can second this. I have experienced it as well, though the problem proved not to be relevant for the document I was working on. I had this bibliography entry from German parliamentary process:

~~~~ bibtex
@legislation{bt12-4022,
author = {{Deutscher Bundestag}},
title = {Entwurf eines Zweiten Gesetzes zur Änderung des Urheberrechtsgesetzes},
number = {BT-Drs. 12/4022},
date = {1992-12-18}}
~~~~

The `Deutscher Bundestag` is the German parliament. It should never be abbreviated, nor is `Bundestag` a surname; Biblatex supports this as what the OP called "literal authors" by an extra pair of braces, though I think Biblatex only supports it for backward compatibility with Bibtex. The problem did not become pressing for me, because this kind of work is cited only by the content of `number` in German judicial articles, so I wrote a CSL style that used `bill` to only print `number`. But I did observe that the author name is not properly parsed while I was writing that citation style.

I want to highlight that Biblatex supports an extended, pretty useful notation for names denoted in the Biblatex manual § 3.4. I have not yet used it, but I will eventually try it out.

**Comment by Quintus** [comment]
> I want to highlight that Biblatex supports an extended, pretty useful notation for names denoted in the Biblatex manual § 3.4. I have not yet used it, but I will eventually try it out.

It's not yet supported. I opened #75 for it.

**Comment by salutis** [comment]
Other examples from my bibliography:

```
author = {{The GLFW Development Team}}
author = {{Purdue University}},
author = {{Hewlett-Packard Company}}
author = {{American Psychological Association}}
author = {{Indiana University}}
...
```

**Comment by salutis** [comment]
@Quintus I would prefer to have 101 BibTeX support first.

**Comment by andras-simonyi** [comment]
@salutis This is the next thing on my ToDo list...

**Comment by salutis** [comment]
@andras-simonyi Thank you so much. I cannot submit a paper for the class due to this issue.

**Comment by Quintus** [comment]
> I would prefer to have 101 BibTeX support first.

Well, and I would prefer other things being done earlier as well. The decision is up to Andras. We should be grateful to Andras that he so voluntaryly implements our requests at all -- it's really great. His incredible work already enabled me to write a scientific paper in org and I never found writing a paper such a pleasure before.

**Comment by salutis** [comment]
@Quintus Agreed. @andras-simonyi = 💣

**Comment by andras-simonyi** [comment]
@Quintus and @salutis  thanks for your kind words, I really appreciate your efforts to try to use citeproc-el and make it better -- the issues you are raising are highly valuable for the development. Incidentally, I've just merged a PR hopefully implementing the double bracket notation for corporate names.

**Comment by salutis** [comment]
Updated to `20211127.936` and the double-bracket names, such as `{{Indiana University}}` work perfectly. Thank you, @andras-simonyi!
